/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  event,
} from './interfaces/event.interface';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CountDown {
    'timestamp': number;
  }
  interface CountDownAttributes extends StencilHTMLAttributes {
    'timestamp'?: number;
  }

  interface DateTime {
    'timestamp': number;
  }
  interface DateTimeAttributes extends StencilHTMLAttributes {
    'timestamp'?: number;
  }

  interface EventCard {
    'event': event;
  }
  interface EventCardAttributes extends StencilHTMLAttributes {
    'event'?: event;
  }

  interface EventForm {}
  interface EventFormAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'CountDown': Components.CountDown;
    'DateTime': Components.DateTime;
    'EventCard': Components.EventCard;
    'EventForm': Components.EventForm;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'count-down': Components.CountDownAttributes;
    'date-time': Components.DateTimeAttributes;
    'event-card': Components.EventCardAttributes;
    'event-form': Components.EventFormAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCountDownElement extends Components.CountDown, HTMLStencilElement {}
  var HTMLCountDownElement: {
    prototype: HTMLCountDownElement;
    new (): HTMLCountDownElement;
  };

  interface HTMLDateTimeElement extends Components.DateTime, HTMLStencilElement {}
  var HTMLDateTimeElement: {
    prototype: HTMLDateTimeElement;
    new (): HTMLDateTimeElement;
  };

  interface HTMLEventCardElement extends Components.EventCard, HTMLStencilElement {}
  var HTMLEventCardElement: {
    prototype: HTMLEventCardElement;
    new (): HTMLEventCardElement;
  };

  interface HTMLEventFormElement extends Components.EventForm, HTMLStencilElement {}
  var HTMLEventFormElement: {
    prototype: HTMLEventFormElement;
    new (): HTMLEventFormElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'count-down': HTMLCountDownElement
    'date-time': HTMLDateTimeElement
    'event-card': HTMLEventCardElement
    'event-form': HTMLEventFormElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'count-down': HTMLCountDownElement;
    'date-time': HTMLDateTimeElement;
    'event-card': HTMLEventCardElement;
    'event-form': HTMLEventFormElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
