/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface EventForm {}
  interface EventFormAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'EventForm': Components.EventForm;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'event-form': Components.EventFormAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEventFormElement extends Components.EventForm, HTMLStencilElement {}
  var HTMLEventFormElement: {
    prototype: HTMLEventFormElement;
    new (): HTMLEventFormElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'event-form': HTMLEventFormElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'event-form': HTMLEventFormElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
