/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface EventForm {}
  interface EventFormAttributes extends StencilHTMLAttributes {}

  interface EventPage {
    'eventId': string;
  }
  interface EventPageAttributes extends StencilHTMLAttributes {
    'eventId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'EventForm': Components.EventForm;
    'EventPage': Components.EventPage;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'event-form': Components.EventFormAttributes;
    'event-page': Components.EventPageAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEventFormElement extends Components.EventForm, HTMLStencilElement {}
  var HTMLEventFormElement: {
    prototype: HTMLEventFormElement;
    new (): HTMLEventFormElement;
  };

  interface HTMLEventPageElement extends Components.EventPage, HTMLStencilElement {}
  var HTMLEventPageElement: {
    prototype: HTMLEventPageElement;
    new (): HTMLEventPageElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'event-form': HTMLEventFormElement
    'event-page': HTMLEventPageElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'event-form': HTMLEventFormElement;
    'event-page': HTMLEventPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
